### ISSUE TITLE
[Bug] Validation issue on valid HTML page

### ISSUE THREAD

**Issue by j9t** [theoludwig/html-w3c-validator#6]
## Steps to reproduce

1. Locally validate [the following HTML](https://mirrors.meiert.org/havewestoppedkillingyet.org/)

(Settings:)

```
{
  "$schema": "https://raw.githubusercontent.com/theoludwig/html-w3c-validator/master/schema/html-w3c-validatorrc-schema.json",
  "files": ["./index.html"],
  "severities": ["info", "warning", "error"]
}
```

## The current behavior

1. “Error: Table must have a consistent number of cells.”

## The expected behavior

1. The document is confirmed valid, [similar to the W3C validator](https://validator.w3.org/check?uri=https%3A%2F%2Fmirrors.meiert.org%2Fhavewestoppedkillingyet.org%2F).

**Comment by theoludwig** [comment]
Hey! :wave: @j9t 

Thank you for your report, indeed, I succesfully reproduced the bug. I'm currently looking into it.

**Comment by theoludwig** [comment]
Issue fixed and released! @j9t 

Your HTML is not "strictly" valid, as there are still a warning for "missing `lang` attribute to the `html` tag", and a error, because you don't specify charset encoding for example with `<meta charset="UTF-8" />`.

The error `"Error: Table must have a consistent number of cells."` occured, because the charset error didn't specified line/column.
Now with v1.7.0, it correctly prints:
```txt
✖ Validating HTML (W3C)...
✖ ./index.html

./index.html
╔═════════╤══════════════════════════════════════════════════════════════════════════════════════════════════════╤═══════════════════════╗
║ error   │ The character encoding was not declared. Proceeding using “windows-1252”.                            │                       ║
╟─────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────╢
║ warning │ Consider adding a “lang” attribute to the “html” start tag to declare the language of this document. │ line: 2, column: 16-7 ║
╚═════════╧══════════════════════════════════════════════════════════════════════════════════════════════════════╧═══════════════════════╝

------------------------------

Error: HTML validation (W3C) failed!
```

If you would like to ignore warnings, you can always configure the severity with `.html-w3c-validatorrc.json`, for example, to only have "error" and not warning or info:

```json
{
  "$schema": "./node_modules/html-w3c-validator/schema/schema.json",
  "files": ["./index.html"],
  "severities": ["error"]
}
```

**Comment by j9t** [comment]
> Issue fixed and released!

Cheers @theoludwig! Will re-test asap.

> Your HTML is not "strictly" valid, as there are still a warning for "missing `lang` attribute to the `html` tag", and a error, because you don't specify charset encoding for example with `<meta charset="UTF-8" />`.
>
> ║ error   │ The character encoding was not declared. Proceeding using “windows-1252”.                            │                       ║

The document in question uses UTF-8, which is [also defined by HTTP header](https://redbot.org/?uri=https%3A%2F%2Fmirrors.meiert.org%2Fhavewestoppedkillingyet.org%2F).

HTML uses [UTF-8 as the default encoding](https://html.spec.whatwg.org/multipage/semantics.html#charset).

There is no requirement to declare the encoding in the file itself.

As such this shouldn’t be an error, and the fallback should probably be UTF-8.

(This looks like a separate issue for html-w3c-validator. Can file one for this, too, if I can reproduce the issue when re-testing.)

> ║ warning │ Consider adding a “lang” attribute to the “html” start tag to declare the language of this document. │ line: 2, column: 16-7 ║

That matches how the W3C validator handles this. The story here is more complicated once you also consider the `Content-Language` header and test language detection and support in user agents, so let’s just say, this is intended. Thanks for pointing it out.
